name: 'Azure Boards, check for AB#'
description: 'Check if the pull request is linked to a work item in Azure DevOps fork of github.com/danhellem/github-actions-pr-is-linked-to-work-item'
author: 'szczepix'
branding:
  icon: "code"
  color: "purple"
inputs:
  repo-token:
    description: 'Github token of the repository (automatically created by GitHub)'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
