name: 'Azure Boards link - PR description contains AB#'
description: 'Check if the pull request contains AB# in the description - Azure Boards link'
author: 'szczepix'
branding:
  icon: "check-square"
  color: "green"
inputs:
  repo-token:
    description: 'Github token of the repository (automatically created by GitHub)'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
